
;this file is automatically generated: Wed Feb 24 16:35:40 GMT 2016

;declarations generated

(declare-fun obj_1430fe31_ab8c_4656_a7f8_16f0200b6bd0 ( Int) Int )
(declare-fun student_year ( Int) Int )
(declare-fun type_0ada7e9f_516a_47b4_b237_381a12cb54be_Student ( Int) Bool )
(declare-fun rel_de1c93ef_0a96_4948_a6a4_f3922081dd04_study ( Int Int) Bool )
(declare-fun module_code ( Int) Int )
(declare-fun module_year ( Int) Int )
(declare-fun module_credit ( Int) Int )
(declare-fun student_id ( Int) Int )
(declare-fun person_age ( Int) Int )
(declare-fun aux2 () Int )
(declare-fun aux3 () Int )
(declare-fun aux0 () Int )
(declare-fun aux1 () Int )
(declare-fun person_mature ( Int) Bool )
(declare-fun type_f7e59a0f_47b3_490d_9411_0cc6a951a247_Person ( Int) Bool )
(declare-fun type_d4dc3ef4_3773_4312_98b4_047e68d6c733_Module ( Int) Bool )

;formulas generated
(assert (and (>= aux0 0) (<= aux0 1)))
(assert (or (or (forall ((p Int)) (=> ( type_f7e59a0f_47b3_490d_9411_0cc6a951a247_Person p )  (< ( person_age ( obj_1430fe31_ab8c_4656_a7f8_16f0200b6bd0 p )  )  18))) (and (= aux0 1) true)) (and (= aux0 0) false)))
(assert (and (>= aux1 0) (<= aux1 1)))
(assert (or (or (forall ((p Int)) (=> ( type_f7e59a0f_47b3_490d_9411_0cc6a951a247_Person p )  (not (= ( person_mature ( obj_1430fe31_ab8c_4656_a7f8_16f0200b6bd0 p )  )  true) ))) (and (= aux1 1) true)) (and (= aux1 0) false)))
(assert (and (>= aux2 0) (<= aux2 1)))
(assert (or (or (forall ((p Int)) (=> (and ( type_0ada7e9f_516a_47b4_b237_381a12cb54be_Student p )  ( type_f7e59a0f_47b3_490d_9411_0cc6a951a247_Person p ) ) (>= ( person_age ( obj_1430fe31_ab8c_4656_a7f8_16f0200b6bd0 p )  )  18))) (and (= aux2 1) true)) (and (= aux2 0) false)))
(assert (and (>= aux3 0) (<= aux3 1)))
(assert (or (or (and (forall ((p Int)) (=> (and ( type_0ada7e9f_516a_47b4_b237_381a12cb54be_Student p )  ( type_f7e59a0f_47b3_490d_9411_0cc6a951a247_Person p ) ) (>= ( student_year ( obj_1430fe31_ab8c_4656_a7f8_16f0200b6bd0 p )  )  1))) (forall ((p Int)) (=> (and ( type_0ada7e9f_516a_47b4_b237_381a12cb54be_Student p )  ( type_f7e59a0f_47b3_490d_9411_0cc6a951a247_Person p ) ) (<= ( student_year ( obj_1430fe31_ab8c_4656_a7f8_16f0200b6bd0 p )  )  6)))) (and (= aux3 1) true)) (and (= aux3 0) false)))
(assert (exists ((p Int)) ( type_d4dc3ef4_3773_4312_98b4_047e68d6c733_Module p ) ))
(assert (exists ((p Int)) ( type_f7e59a0f_47b3_490d_9411_0cc6a951a247_Person p ) ))
(assert (exists ((p Int)) (and ( type_0ada7e9f_516a_47b4_b237_381a12cb54be_Student p )  ( type_f7e59a0f_47b3_490d_9411_0cc6a951a247_Person p ) )))
(assert (= (+ (+ (+ aux0 aux1) aux2) aux3) 0))

 ;end of formula 
